### ISSUE TITLE
Add information about update-ability, default value, & validation

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-plugin-docs#398]
### Terraform CLI and terraform-plugin-docs Versions

latest

### Use Cases or Problem Statement

It would be nice for users to know more about a parameters behaviors without having to write lengthy custom descriptions. It would also be nice to be able to have a unified look to documentation so common questions are answered uniformly and generated instead of hand typed.

Specifically it would be nice to know a parameters:
- default value - if applicable
- updateability - if it can be updated or requires replacement

### Proposal

Technical implementation is currently limited by missing fields in the [schema](https://github.com/hashicorp/terraform/issues/35646). That aside, here are some proposals for how to display the information:

```yaml
- `my_parameter` <description>
  - Type: <type>  
  - Default: "one"
  - Plan Modifiers: 
    - Forces Recreation
  - Validators:
    - Any one of: `one`, `two`, `three`
  ```

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
